"""Add farmer_id to farmers table

Revision ID: 3dce66df8987
Revises: 375b03bcd37b
Create Date: 2026-02-22 14:37:16.450470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dce66df8987'
down_revision: Union[str, None] = '375b03bcd37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('farmer_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_farmers_farmer_id'), 'farmers', ['farmer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmers_farmer_id'), table_name='farmers')
    op.drop_column('farmers', 'farmer_id')
    # ### end Alembic commands ###
