"""Initial migration

Revision ID: cf07e7adf8bb
Revises: 
Create Date: 2026-02-22 11:11:38.634150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf07e7adf8bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nin', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FARMER', name='userrole'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_nin'), 'users', ['nin'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('nin', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('personal_address', sa.String(), nullable=True),
    sa.Column('personal_state', sa.String(), nullable=True),
    sa.Column('personal_lga', sa.String(), nullable=True),
    sa.Column('farm_address', sa.String(), nullable=True),
    sa.Column('farm_state', sa.String(), nullable=True),
    sa.Column('farm_lga', sa.String(), nullable=True),
    sa.Column('farm_size', sa.Float(), nullable=True),
    sa.Column('crop_type', sa.String(), nullable=True),
    sa.Column('livestock_type', sa.String(), nullable=True),
    sa.Column('farm_status', sa.Enum('PENDING', 'VERIFIED', name='farmstatus'), nullable=True),
    sa.Column('farmer_status', sa.Enum('PENDING', 'PROCESSING', 'APPROVED', 'DENIED', name='farmerstatus'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_farmers_email'), 'farmers', ['email'], unique=False)
    op.create_index(op.f('ix_farmers_full_name'), 'farmers', ['full_name'], unique=False)
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_index(op.f('ix_farmers_nin'), 'farmers', ['nin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmers_nin'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_full_name'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_email'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_nin'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
